load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "assem_bunny",
    srcs = ["assem_bunny.cc"],
    hdrs = ["assem_bunny.h"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//advent_of_code:advent_day",
        "@com_google_absl//absl/container:flat_hash_set",
        "@com_google_absl//absl/log",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@com_googlesource_code_re2//:re2",
    ],
)

cc_library(
    name = "2016",
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//advent_of_code/2016/day01",
        "//advent_of_code/2016/day02",
        "//advent_of_code/2016/day03",
        "//advent_of_code/2016/day04",
        "//advent_of_code/2016/day05",
        "//advent_of_code/2016/day06",
        "//advent_of_code/2016/day07",
        "//advent_of_code/2016/day08",
        "//advent_of_code/2016/day09",
        "//advent_of_code/2016/day10",
        "//advent_of_code/2016/day11",
        "//advent_of_code/2016/day12",
        "//advent_of_code/2016/day13",
        "//advent_of_code/2016/day14",
        "//advent_of_code/2016/day15",
        "//advent_of_code/2016/day16",
        "//advent_of_code/2016/day17",
        "//advent_of_code/2016/day18",
        "//advent_of_code/2016/day19",
        "//advent_of_code/2016/day20",
        "//advent_of_code/2016/day21",
        "//advent_of_code/2016/day22",
        "//advent_of_code/2016/day23",
        "//advent_of_code/2016/day24",
        "//advent_of_code/2016/day25",
    ],
)
