cc_test(
    name = "benchmark",
    tags = ["benchmark"],
    deps = [
        "//advent_of_code/2022/day01:day01_benchmark_lib",
        "//advent_of_code/2022/day02:day02_benchmark_lib",
        "//advent_of_code/2022/day03:day03_benchmark_lib",
        "//advent_of_code/2022/day04:day04_benchmark_lib",
        "//advent_of_code/2022/day05:day05_benchmark_lib",
        "//advent_of_code/2022/day06:day06_benchmark_lib",
        "//advent_of_code/2022/day07:day07_benchmark_lib",
        "//advent_of_code/2022/day08:day08_benchmark_lib",
        "//advent_of_code/2022/day09:day09_benchmark_lib",
        "//advent_of_code/2022/day10:day10_benchmark_lib",
        "//advent_of_code/2022/day11:day11_benchmark_lib",
        "//advent_of_code/2022/day12:day12_benchmark_lib",
        "//advent_of_code/infra:gunit_main",
    ],
)
