cc_test(
    name = "benchmark",
    tags = ["benchmark"],
    deps = [
        "//advent_of_code/2022/day01:day01_benchmark_lib",
        "//advent_of_code/2022/day02:day02_benchmark_lib",
        "@com_monkeynova_gunit_main//:test_main",
    ],
)
