cc_library(
    name = "2024",
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//advent_of_code/2024/day01",
        "//advent_of_code/2024/day02",
        "//advent_of_code/2024/day03",
        "//advent_of_code/2024/day04",
        "//advent_of_code/2024/day05",
        "//advent_of_code/2024/day06",
        "//advent_of_code/2024/day07",
        "//advent_of_code/2024/day08",
        "//advent_of_code/2024/day09",
        "//advent_of_code/2024/day10",
        "//advent_of_code/2024/day11",
        "//advent_of_code/2024/day12",
        "//advent_of_code/2024/day13",
        "//advent_of_code/2024/day14",
        "//advent_of_code/2024/day15",
        "//advent_of_code/2024/day16",
    ],
)
